### PR TITLE
Handle unavailable composer.json on private repo (issue #76)

### PR DESCRIPTION
**Pull request by emirpprime**
- Warning, not Error, when composer.json cannot be retrieved
- Return best-guess $package_name

### CODE REVIEW

**Comment by emirpprime** [comment]
Realised I've broken other tests. Fixing.

**Comment by emirpprime** [comment]
Previous test failed due to OOM error, but I realised that array dereferencing isn't supported in 5.3 anyway so I've updated to remove that.

**Comment by emirpprime** [comment]
OOM again ¯\_(ツ)_/¯

**Comment by danielbachhuber** [comment]
I've merged master.

**Comment by schlessera** [comment]
Thanks for the pull request, @emirpprime !

**Pull request merged**
