### PR TITLE
support GitLab.com URL (#110)

### LINKED ISSUE #110: check_git_package_name hardcode reference to GitHub
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

`wp package install https://gitlab.com/my/package.git`

=>
```
Warning: Couldn't download composer.json file from 'https://raw.githubusercontent.com/my/package/master/composer.json' (HTTP code 404).
Presuming package name is 'my/package'.
```

Repository is at **gitlab**.com, "real" name must not be checked at raw.**github**usercontent.com

This breaks further package name resolution if the repository name is not the same than the package name.

### PR DESCRIPTION
**Pull request by drzraf**
fixes #110

### CODE REVIEW

**Comment by schlessera** [comment]
@drzraf The reason for why this build failed tests was fixed in the framework. Can you merge latest `master` into this PR? It should fix the tests then.

**Comment by drzraf** [comment]
friendly ping

**Comment by schlessera** [comment]
Thanks for the PR, @drzraf !

**Comment by drzraf** [comment]
I wonder. PR reached 2.0.7 which was released **after** the latest stable release of `wp-cli`.
I tried to override Phar built-in's `package` command (`wp package install wp-cli/package-command:2.0.9`), but I'm said that `package-command` requires `wp-cli/wp-cli ~2.5`. (I'm on 2.4.0)

Does it mean I've no way to benefit from the PR, even though a `package-command` release happened until a new release of `wp-cli` itself is done? (It's annoying because I'd like to avoid using a non-stable release of wp-cli for this particular usage and only use an updated version of the `package-commad`).

**Comment by schlessera** [comment]
@drzraf I just now noticed this comment, unfortunately.

Normally I don't add such strict requirements to the packages. This was made necessary because there was so much breakage and compact issues from v2.4.0 to v2.5.0. You could always try to use a custom alias in your  `$HOME/.wp-cli/packages/composer.json` file. Or, what's easier, is to switch to latest WP-CLI `--nightly` release instead, which works for fulfilling the `^2.5.0` requirements. Nightly would not normally make sense for production use, but given that PHP 8 and WP pretty flat-out broke v2.4.0, v2.5.0 is actually the much more stable one.

However, all of this is probably to late for you now anyway, as I'm about to push release v2.5.0 out in an hour or so, which means v2.5.0 will be the latest stable.

**Pull request merged**
