### PR TITLE
GH#29 Added depreciation notice

### LINKED ISSUE #29: Notice when browsing the package index
As we have now deprecated the package index, and have not yet decided about what discovery mechanism we might implement, we should display a notice when running `wp package browse` about this.

I'm thinking about something like this:

```
Although the package index will remain in place for backward compatibility reasons, it has been deprecated and will not be updated further.
Please refer to https://github.com/wp-cli/ideas/issues/51 to read about its potential replacement.
```

### PR DESCRIPTION
**Pull request by Sidsector9**
Fixes #29

### CODE REVIEW

**Comment by Sidsector9** [comment]
@danielbachhuber, part of the function doc block?

**Comment by miya0001** [comment]
@Sidsector9 

We should update following lines.

https://github.com/Sidsector9/package-command/blob/76844055dbc8edc6e20ec45a102e0c77338f21c8/src/Package_Command.php#L116-L136

**Comment by Sidsector9** [comment]
@miya0001 can you confirm if this is updated correctly?

**Comment by miya0001** [comment]
If you run `wp package browse --format=yaml`, then we can see like following.
There should be notice which is added by this PR.

```
$ wp package browse --format=yaml
Although the package index will remain in place for backward compatibility reasons, it has been deprecated and will not be updated further.
Please refer to https://github.com/wp-cli/ideas/issues/51 to read about its potential replacement.
---
- 
  name: 10up/mu-migration
  description: A set of WP-CLI commands to support the migration of single WordPress instances to multisite
  authors: Nícholas André
  version: dev-master, dev-develop, dev-feature/tables-param, dev-feature/users-mapping-improvements
```

So, we should add same notice to the following example. :)
https://github.com/Sidsector9/package-command/blob/76844055dbc8edc6e20ec45a102e0c77338f21c8/src/Package_Command.php#L116-L136

**Comment by danielbachhuber** [comment]
@Sidsector9 @miya0001 Although it's probably not an issue in this case, we should avoid breaking machine-readable output (e.g. don't display notices when `--format=(yaml|json)`

**Pull request merged**
