### PR TITLE
Install WP-CLI with Composer in tests to introduce `utils/make-phar.php`

### LINKED ISSUE #1: Tests fail because utils/make-phar.php isn't accessible
See https://travis-ci.org/wp-cli/package-command/builds/209899744

```
01. $ php -dphar.readonly=0 'features/bootstrap/../../utils/make-phar.php' '/tmp/wp-cli-test-run-58c317feeaf023.95759079/wp-cli-build-58c317feeaff24.74413409.phar' --version='0.23.0' && chmod +x '/tmp/wp-cli-test-run-58c317feeaf023.95759079/wp-cli-build-58c317feeaff24.74413409.phar'
    Could not open input file: features/bootstrap/../../utils/make-phar.php
```

Which option makes more sense?

1. Include `utils/make-phar.php` as a one-off in this repo.
2. Add `utils/make-phar.php` to `wp scaffold package-tests` so that the Phar creation step is available to every WP-CLI command.
3. Add `utils/make-phar.php` to the generated WP-CLI Phar file, so that it's available 

I'm leaning towards 3 at this point, so there's always one source of truth for Phar generation.

### LINKED ISSUE #3: Tests in `wp-cli/wp-cli` fail because of Composer conflict
Composer has a conflict between `wp-cli/wp-cli@dev-master` and `wp-cli/wp-cli@1.2.0-alpha` (See https://github.com/wp-cli/wp-cli/issues/3933)

This should be resolvable through a proper branch alias of `"dev-master": "1.x-dev"`.

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes #1 
Fixes #3
Uses https://github.com/wp-cli/scaffold-package-command/pull/89

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@schlessera I don't think https://github.com/wp-cli/wp-cli/pull/3921 fixed this issue. Composer still returns this error:

```
  Problem 1
    - Installation request for wp-cli/package-command dev-2a4ac19b859ac77c92e60efc972e539c6b834fb1 -> satisfiable by wp-cli/package-command[dev-2a4ac19b859ac77c92e60efc972e539c6b834fb1].
    - wp-cli/wp-cli dev-master requires wp-cli/package-command ^1.0 -> satisfiable by wp-cli/package-command[v1.0.0].
    - Can only install one of: wp-cli/package-command[v1.0.0, dev-2a4ac19b859ac77c92e60efc972e539c6b834fb1].
    - Installation request for wp-cli/wp-cli dev-master -> satisfiable by wp-cli/wp-cli[dev-master].
```

**Comment by schlessera** [comment]
The issue is that Composer cannot rely on the fact that your dev branch automatically meets the `^1.0` requirement (it could include a breaking change, it could be something entirely different, ...).

That's why you need to explicitly tell it that your dev branch matches that requirement. You can do so by adding a branch alias to the `wp-cli/package-command`:
```
    "extra": {
        "branch-alias": {
            "dev-master": "1.0.x-dev"
        }
    }
```

**Comment by schlessera** [comment]
You have `"minimum-stability": "dev"` in the `composer.json` file. You need to add `"prefer-stable": true` as well, otherwise it will pull down the dev version of every single dependency, instead of the stable ones.

**Comment by danielbachhuber** [comment]
@schlessera Here's the fatal from removing the `class_exists()` check:

image

Also, we seem to be pulling in `dev-master` for `composer/composer` too. Is there a way to tie `branch-alias` to a specific project?

**Comment by danielbachhuber** [comment]
From our phone call today, the fatal from removing the `class_exists()` check is probably because the autoloader is bundled in the Phar, and then loaded a second time by `package-command.php` at a different path.

**Comment by schlessera** [comment]
The prefer-stable should fix the issue of having the `dev-master` of `composer/composer` be pulled in.

But just for future reference, you can also define package-specific aliases from within the requiring package by adding them to the version string as follows:
```
require: {
   "vendor/package": "dev-whatever-branch as 1.2.5"
}
```

**Comment by schlessera** [comment]
Some more specifics about the fatal:
Normally, the `require_once` directive would avoid loading the Composer autoloader a second time. However, in this case, as the paths are different (`file:///some/folder/vendor/autoload.php` vs `phar:///vendor/autoload.php`), the require_once doesn't recognize them being the same file.

**Comment by danielbachhuber** [comment]
Chatted in Slack, and decided to go with `class_exists()` for now https://wordpress.slack.com/archives/C02RP4T41/p1490886655640052

**Comment by schlessera** [comment]
I think that the test failures after the latest changes are due to changed behaviour because of switching from included `wp package` to Composer-packaged `wp package`.

We will probably need to rethink these tests.

**Comment by danielbachhuber** [comment]
@schlessera I've just pushed some changes. The build should pass now.

**Comment by schlessera** [comment]
The build still fails. It seems to be able to pull in `wp-cli/google-sitemap-generator-cli.git`:
```
Warning: Failed to execute git clone --mirror 'git@github.com:wp-cli/google-sitemap-generator-cli.git' '/tmp/wp-cli-home/.composer/cache/vcs/git-github.com-wp-cli-google-sitemap-generator-cli.git/'
```

Maybe GitHub rate limit?

**Comment by danielbachhuber** [comment]
> Maybe GitHub rate limit?

Must be. It's flagged with the `@github-api` decorator. Test passes locally.

Updated to use `./bin/test.sh` in 12f8777d

**Pull request merged**
